"""Where every number came from, carried alongside the number.

This engine mixes measured satellite records with claim-side figures taken from
project documents, and during development some inputs are synthetic fixtures.
Those are three very different epistemic objects and conflating them is the
single most damaging thing a verification tool can do. So provenance is not
metadata bolted on at the edge - it travels with the data and is propagated into
every result, and the pipeline refuses to describe a result as a finding if any
input to it was synthetic or illustrative.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Provenance(str, Enum):
    """What kind of thing a number is."""

    MEASURED = "measured"
    """Observed from a public dataset. Carries a citation."""

    REPORTED = "reported"
    """Taken from a project document or registry record. Real, but a claim made
    by an interested party rather than an independent observation."""

    ILLUSTRATIVE = "illustrative"
    """A stand-in that resembles a real record but describes no real party.
    Legitimate for exercising the interface; never a basis for a finding."""

    SYNTHETIC = "synthetic"
    """Generated by a fixture for testing. Has no relationship to any real
    forest and must never reach a user-facing result unlabelled."""

    MODELLED = "modelled"
    """Produced by this engine from measured inputs."""


@dataclass(frozen=True)
class DataProvenance:
    """The provenance of one dataset."""

    kind: Provenance
    source: str
    citation: str = ""
    license: str = ""
    collected_at: str = ""
    note: str = ""

    @property
    def is_real(self) -> bool:
        """True when this describes actual observed land or a real record."""
        return self.kind in (Provenance.MEASURED, Provenance.REPORTED)

    def describe(self) -> str:
        return f"{self.kind.value}: {self.source}" + (f" ({self.citation})" if self.citation else "")


@dataclass(frozen=True)
class ResultProvenance:
    """Provenance of a finished analysis, split by side of the comparison.

    The distinction that matters to a reader is which half of the comparison is
    real. A discrepancy computed from a measured counterfactual against an
    illustrative claim is a real measurement of an imaginary claim: useful for
    demonstrating the method, worthless as a finding about a project.
    """

    measurement: DataProvenance
    claim: DataProvenance

    @property
    def is_finding(self) -> bool:
        """Whether this may be presented as a statement about a real project."""
        return self.measurement.is_real and self.claim.is_real

    @property
    def caveat(self) -> str:
        if self.is_finding:
            return ""
        if self.measurement.kind == Provenance.SYNTHETIC:
            return (
                "SYNTHETIC FIXTURE - both sides of this comparison are generated test data. "
                "It demonstrates that the algorithm runs; it says nothing about any forest."
            )
        if not self.claim.is_real:
            return (
                "The measured side of this comparison is real; the claimed baseline and credit "
                "volumes are illustrative and describe no real project. The discrepancy is "
                "therefore an exercise of the method, not a finding about any party."
            )
        return "This result contains inputs that are not independently measured."
