// cells.js — the control pool.
//
// One record per 1-degree parcel of the Brazilian Legal Amazon, measured from
// INPE PRODES (deforestation) and Open-Meteo (terrain, rainfall). Generated by
// tools/collect.mjs; see cells.json for provenance. Nothing here is modelled.

import data from "./cells.json";

export const CELLS = data.cells;
export const CELLS_META = {
  source: data.source,
  citation: data.citation,
  license: data.license,
  collectedAt: data.collectedAt,
  region: data.region,
  cellDegrees: data.cellDegrees,
  firstYear: data.firstYear,
  lastYear: data.lastYear,
};

/** The parcel a point falls in, or null. */
export const cellAt = (lon, lat) =>
  CELLS.find((c) => lon >= c.bbox[0] && lon < c.bbox[2] && lat >= c.bbox[1] && lat < c.bbox[3]) ?? null;
