// data.js — the FICTIONAL layer, kept strictly separate from the real one.
//
// Project boundaries, names, registry IDs, credit volumes, claimed baselines and
// every buyer below are invented for this demo. No real project, registry entry
// or company is named anywhere.
//
// What is NOT invented: the forest measurements these polygons are scored on.
// Those are read from UMD/Hansen Global Forest Change (Landsat, 30 m) at the real
// coordinates below — see measurements.json and forestData.js.
//
// Generated by scratchpad/finalize.mjs. Areas in hectares, centres in [lon, lat].

export const REGION = {
  name: "Brazilian Amazon",
  sub: "Arc of deforestation",
  center: [-57.5, -6.5],
  zoom: 4.4,
  maxBounds: [[-73.5, -16.5], [-42.5, 4.5]],
};

export const PROJECTS = [
  {
    "id": "AMZ-4374",
    "name": "Igarapé Branco Conservation",
    "state": "Mato Grosso",
    "center": [
      -55,
      -11
    ],
    "areaHa": 61000,
    "creditsIssued": 305000,
    "claimedBaselineLoss": 0.22,
    "seed": 4374
  },
  {
    "id": "AMZ-4237",
    "name": "Rio Piraquara Reserve",
    "state": "Mato Grosso",
    "center": [
      -53,
      -12
    ],
    "areaHa": 96000,
    "creditsIssued": 768000,
    "claimedBaselineLoss": 0.33,
    "seed": 4237
  },
  {
    "id": "AMZ-4511",
    "name": "Alto Tapiranga REDD+",
    "state": "Maranhão",
    "center": [
      -46,
      -2
    ],
    "areaHa": 187000,
    "creditsIssued": 2057000,
    "claimedBaselineLoss": 0.33,
    "seed": 4511
  },
  {
    "id": "AMZ-4100",
    "name": "Serra do Cajueiro REDD+",
    "state": "Mato Grosso",
    "center": [
      -52,
      -10
    ],
    "areaHa": 148000,
    "creditsIssued": 2072000,
    "claimedBaselineLoss": 0.3,
    "seed": 4100
  },
  {
    "id": "AMZ-5196",
    "name": "Ipê Amarelo Conservation",
    "state": "Amazonas",
    "center": [
      -54,
      -6
    ],
    "areaHa": 53000,
    "creditsIssued": 901000,
    "claimedBaselineLoss": 0.25,
    "seed": 5196
  },
  {
    "id": "AMZ-4648",
    "name": "Castanhal Verde Project",
    "state": "Amazonas",
    "center": [
      -61,
      -8
    ],
    "areaHa": 42000,
    "creditsIssued": 840000,
    "claimedBaselineLoss": 0.36,
    "seed": 4648
  },
  {
    "id": "AMZ-4785",
    "name": "Vale do Jatobá REDD+",
    "state": "Rondônia",
    "center": [
      -62,
      -10
    ],
    "areaHa": 118000,
    "creditsIssued": 590000,
    "claimedBaselineLoss": 0.35,
    "seed": 4785
  },
  {
    "id": "AMZ-5059",
    "name": "Serra Dourada Reserve",
    "state": "Amazonas",
    "center": [
      -56,
      -1
    ],
    "areaHa": 165000,
    "creditsIssued": 1320000,
    "claimedBaselineLoss": 0.34,
    "seed": 5059
  },
  {
    "id": "AMZ-5607",
    "name": "Barra do Anil Reserve",
    "state": "Rondônia",
    "center": [
      -61,
      -12
    ],
    "areaHa": 29000,
    "creditsIssued": 319000,
    "claimedBaselineLoss": 0.33,
    "seed": 5607
  },
  {
    "id": "AMZ-4922",
    "name": "Boa Esperança Forest Carbon",
    "state": "Pará",
    "center": [
      -52,
      -7
    ],
    "areaHa": 74000,
    "creditsIssued": 1036000,
    "claimedBaselineLoss": 0.36,
    "seed": 4922
  },
  {
    "id": "AMZ-5470",
    "name": "Campo Sereno Forest Project",
    "state": "Pará",
    "center": [
      -51,
      -1
    ],
    "areaHa": 88000,
    "creditsIssued": 1496000,
    "claimedBaselineLoss": 0.3,
    "seed": 5470
  },
  {
    "id": "AMZ-5333",
    "name": "Rio Cristalino REDD+",
    "state": "Pará",
    "center": [
      -53,
      -1
    ],
    "areaHa": 132000,
    "creditsIssued": 2640000,
    "claimedBaselineLoss": 0.3,
    "seed": 5333
  }
];

export const COMPANIES = [
  {
    "id": "meridian",
    "name": "Meridian Logistics",
    "sector": "Freight & shipping",
    "holdings": [
      {
        "projectId": "AMZ-5059",
        "credits": 270000,
        "pricePerCredit": 7.93,
        "year": 2019
      },
      {
        "projectId": "AMZ-4237",
        "credits": 315000,
        "pricePerCredit": 8.43,
        "year": 2020
      },
      {
        "projectId": "AMZ-4785",
        "credits": 305000,
        "pricePerCredit": 7.95,
        "year": 2021
      },
      {
        "projectId": "AMZ-5333",
        "credits": 50000,
        "pricePerCredit": 5.37,
        "year": 2022
      },
      {
        "projectId": "AMZ-4374",
        "credits": 90000,
        "pricePerCredit": 7.42,
        "year": 2023
      },
      {
        "projectId": "AMZ-5607",
        "credits": 165000,
        "pricePerCredit": 5.12,
        "year": 2024
      }
    ]
  },
  {
    "id": "halcyon",
    "name": "Halcyon Airways",
    "sector": "Aviation",
    "holdings": [
      {
        "projectId": "AMZ-4100",
        "credits": 340000,
        "pricePerCredit": 4.79,
        "year": 2020
      },
      {
        "projectId": "AMZ-4237",
        "credits": 195000,
        "pricePerCredit": 5.72,
        "year": 2021
      },
      {
        "projectId": "AMZ-5607",
        "credits": 240000,
        "pricePerCredit": 7.55,
        "year": 2022
      },
      {
        "projectId": "AMZ-5470",
        "credits": 115000,
        "pricePerCredit": 4.43,
        "year": 2023
      },
      {
        "projectId": "AMZ-4648",
        "credits": 240000,
        "pricePerCredit": 3.2,
        "year": 2024
      },
      {
        "projectId": "AMZ-4374",
        "credits": 130000,
        "pricePerCredit": 8.17,
        "year": 2025
      },
      {
        "projectId": "AMZ-4922",
        "credits": 285000,
        "pricePerCredit": 5.97,
        "year": 2019
      }
    ]
  },
  {
    "id": "vantara",
    "name": "Vantara Consumer Goods",
    "sector": "Consumer goods",
    "holdings": [
      {
        "projectId": "AMZ-5333",
        "credits": 290000,
        "pricePerCredit": 6.44,
        "year": 2021
      },
      {
        "projectId": "AMZ-4374",
        "credits": 340000,
        "pricePerCredit": 8.18,
        "year": 2022
      },
      {
        "projectId": "AMZ-5607",
        "credits": 200000,
        "pricePerCredit": 9.06,
        "year": 2023
      },
      {
        "projectId": "AMZ-4100",
        "credits": 165000,
        "pricePerCredit": 6.94,
        "year": 2024
      },
      {
        "projectId": "AMZ-5059",
        "credits": 325000,
        "pricePerCredit": 6.16,
        "year": 2025
      }
    ]
  },
  {
    "id": "northwind",
    "name": "Northwind Data Centers",
    "sector": "Cloud infrastructure",
    "holdings": [
      {
        "projectId": "AMZ-5196",
        "credits": 235000,
        "pricePerCredit": 6.23,
        "year": 2022
      },
      {
        "projectId": "AMZ-5059",
        "credits": 220000,
        "pricePerCredit": 9.16,
        "year": 2023
      },
      {
        "projectId": "AMZ-4374",
        "credits": 185000,
        "pricePerCredit": 9.49,
        "year": 2024
      },
      {
        "projectId": "AMZ-5333",
        "credits": 65000,
        "pricePerCredit": 6.94,
        "year": 2025
      },
      {
        "projectId": "AMZ-4922",
        "credits": 250000,
        "pricePerCredit": 4.24,
        "year": 2019
      }
    ]
  },
  {
    "id": "aurelia",
    "name": "Aurelia Energy Group",
    "sector": "Power generation",
    "holdings": [
      {
        "projectId": "AMZ-4785",
        "credits": 75000,
        "pricePerCredit": 9.54,
        "year": 2023
      },
      {
        "projectId": "AMZ-4374",
        "credits": 85000,
        "pricePerCredit": 4.85,
        "year": 2024
      },
      {
        "projectId": "AMZ-4237",
        "credits": 70000,
        "pricePerCredit": 7.62,
        "year": 2025
      },
      {
        "projectId": "AMZ-5059",
        "credits": 180000,
        "pricePerCredit": 7.54,
        "year": 2019
      },
      {
        "projectId": "AMZ-5333",
        "credits": 50000,
        "pricePerCredit": 3.59,
        "year": 2020
      },
      {
        "projectId": "AMZ-5196",
        "credits": 40000,
        "pricePerCredit": 3.97,
        "year": 2021
      }
    ]
  }
];
