// projects-kariba.js — GENERATED by tools/make-project-kariba.mjs. Do not edit by hand.
//
// Kariba REDD+ (VCS 902) is a REAL, registered project ("real": true) —
// its registry status, area, timeline and the Verra finding are real
// published facts, sourced in src/caseStudies.js. Its boundary is an
// approximation (see this file's header comment and boundaryApproximate
// below); what is directly measured is Hansen-derived forest loss over that
// approximate footprint, via the legacy GFW v1 API (tools/gfw.mjs), since
// PRODES does not cover Zimbabwe.
//
// The rest are illustrative, built the same way src/projects.js's Amazon
// projects are: real measured footprints, invented claims and credits.

export const REGION = {
  name: "Zambezi Valley, Zimbabwe",
  center: [31, -16.36],
  zoom: 6.2,
  bounds: [[27.68, -17.61], [34.32, -15.11]],
  reach: [[27.3, -19.61], [34.3, -14.6]],
  slack: 0.3,
  maxBounds: [[26.3, -20.3], [35.3, -13.9]],
  window: [2016, 2019],
  referencePeriod: [2008, 2015],
};

export const PROJECTS = [
  {
    "id": "KARIBA-902",
    "name": "Kariba REDD+ Project",
    "shortName": "Kariba REDD+",
    "country": "Zimbabwe",
    "locality": "Binga / Hurungwe / Nyaminyami / Mbire",
    "center": [
      28.44,
      -16.725
    ],
    "areaHa": 758000,
    "seed": 902,
    "registry": "VCS 902, withdrawn from the Verra registry, May 2024",
    "methodology": "VM0009 (avoided unplanned deforestation, reference region)",
    "startYear": 2011,
    "creditingYears": 12,
    "claimedBaselineLoss": 0.14,
    "creditsIssued": 26822953,
    "creditsRetired": null,
    "pricePerCredit": null,
    "featured": true,
    "real": true,
    "boundaryApproximate": true,
    "boundary": [
      [
        27.7,
        -16.95
      ],
      [
        27.68,
        -16.75
      ],
      [
        27.85,
        -16.55
      ],
      [
        28.2,
        -16.48
      ],
      [
        28.6,
        -16.45
      ],
      [
        29,
        -16.5
      ],
      [
        29.2,
        -16.62
      ],
      [
        29.18,
        -16.8
      ],
      [
        28.95,
        -16.92
      ],
      [
        28.5,
        -16.98
      ],
      [
        28.05,
        -17
      ],
      [
        27.7,
        -16.95
      ]
    ],
    "hostCellId": null,
    "parcel": {
      "id": "KARIBA-902-footprint",
      "bbox": [
        27.68,
        -17,
        29.2,
        -16.45
      ],
      "center": [
        28.44,
        -16.725
      ],
      "label": "Binga / Hurungwe / Nyaminyami / Mbire",
      "areaKm2": 7886,
      "landKm2": 7886,
      "forest2008Km2": 121,
      "preClearedKm2": 3.4,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 0.639,
        "2009": 1.741,
        "2010": 0.407,
        "2011": 0.566,
        "2012": 0.261,
        "2013": 0.488,
        "2014": 0.554,
        "2015": 0.611,
        "2016": 0.719,
        "2017": 0.823,
        "2018": 0.37,
        "2019": 0.486
      },
      "protectedFrac": 0.15,
      "elevationM": null,
      "ruggednessM": null,
      "precipMmYr": null
    }
  },
  {
    "id": "KZ-1100",
    "name": "Chizarira REDD+",
    "shortName": "Chizarira",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      33.55,
      -15.35
    ],
    "areaHa": 240000,
    "seed": 1100,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.043,
    "creditsIssued": 360000,
    "creditsRetired": 108000,
    "pricePerCredit": 4.5,
    "featured": false,
    "real": false,
    "hostCellId": "KZ33.3_-15.6",
    "parcel": {
      "id": "KZ-1100-footprint",
      "bbox": [
        33.3218,
        -15.5715,
        33.7782,
        -15.1285
      ],
      "center": [
        33.55,
        -15.35
      ],
      "label": null,
      "areaKm2": 2416.1,
      "landKm2": 2416.1,
      "forest2008Km2": 690.9,
      "preClearedKm2": 15.2,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 9.233,
        "2009": 0.878,
        "2010": 0.39,
        "2011": 0.33,
        "2012": 2.416,
        "2013": 2.383,
        "2014": 3.526,
        "2015": 5.011,
        "2016": 6.451,
        "2017": 7.121,
        "2018": 3.687,
        "2019": 4.843
      },
      "protectedFrac": 0,
      "elevationM": 576,
      "ruggednessM": 177,
      "precipMmYr": 878
    }
  },
  {
    "id": "KZ-1173",
    "name": "Mafungabusi Forest Project",
    "shortName": "Mafungabusi",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      30.05,
      -16.35
    ],
    "areaHa": 180000,
    "seed": 1173,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.03,
    "creditsIssued": 190000,
    "creditsRetired": 72200,
    "pricePerCredit": 8,
    "featured": false,
    "real": false,
    "hostCellId": "KZ29.8_-16.6",
    "parcel": {
      "id": "KZ-1173-footprint",
      "bbox": [
        29.8514,
        -16.5418,
        30.2486,
        -16.1582
      ],
      "center": [
        30.05,
        -16.35
      ],
      "label": null,
      "areaKm2": 1811.8,
      "landKm2": 1811.8,
      "forest2008Km2": 51.6,
      "preClearedKm2": 1.5,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 0.114,
        "2009": 0.215,
        "2010": 0.298,
        "2011": 0.067,
        "2012": 0.122,
        "2013": 0.02,
        "2014": 0.022,
        "2015": 0.082,
        "2016": 0.153,
        "2017": 0.065,
        "2018": 0.012,
        "2019": 0.016
      },
      "protectedFrac": 0,
      "elevationM": 693,
      "ruggednessM": 210,
      "precipMmYr": 760
    }
  },
  {
    "id": "KZ-1246",
    "name": "Sijarira Conservation Concession",
    "shortName": "Sijarira",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      33.05,
      -17.35
    ],
    "areaHa": 90000,
    "seed": 1246,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.03,
    "creditsIssued": 90000,
    "creditsRetired": 41400,
    "pricePerCredit": 7,
    "featured": false,
    "real": false,
    "hostCellId": "KZ32.8_-17.6",
    "parcel": {
      "id": "KZ-1246-footprint",
      "bbox": [
        32.9088,
        -17.4857,
        33.1912,
        -17.2143
      ],
      "center": [
        33.05,
        -17.35
      ],
      "label": null,
      "areaKm2": 906.6,
      "landKm2": 906.6,
      "forest2008Km2": 69.5,
      "preClearedKm2": 0.6,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 0.111,
        "2009": 0.16,
        "2010": 0.185,
        "2011": 0.007,
        "2012": 0.392,
        "2013": 0.138,
        "2014": 0.272,
        "2015": 0.417,
        "2016": 0.211,
        "2017": 0.154,
        "2018": 0.099,
        "2019": 0.157
      },
      "protectedFrac": 0,
      "elevationM": 636,
      "ruggednessM": 96,
      "precipMmYr": 622
    }
  },
  {
    "id": "KZ-1319",
    "name": "Dande Valley REDD+",
    "shortName": "Dande Valley",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      31.55,
      -15.35
    ],
    "areaHa": 260000,
    "seed": 1319,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.03,
    "creditsIssued": 270000,
    "creditsRetired": 145800,
    "pricePerCredit": 6,
    "featured": false,
    "real": false,
    "hostCellId": "KZ31.3_-15.6",
    "parcel": {
      "id": "KZ-1319-footprint",
      "bbox": [
        31.3125,
        -15.5806,
        31.7875,
        -15.1194
      ],
      "center": [
        31.55,
        -15.35
      ],
      "label": null,
      "areaKm2": 2617.9,
      "landKm2": 2617.9,
      "forest2008Km2": 217.6,
      "preClearedKm2": 13.5,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 1.528,
        "2009": 2.702,
        "2010": 0.572,
        "2011": 0.247,
        "2012": 0.249,
        "2013": 1.13,
        "2014": 1.134,
        "2015": 0.411,
        "2016": 0.743,
        "2017": 1.255,
        "2018": 0.472,
        "2019": 0.647
      },
      "protectedFrac": 0,
      "elevationM": 778,
      "ruggednessM": 95,
      "precipMmYr": 811
    }
  },
  {
    "id": "KZ-1392",
    "name": "Nyakasanga Forest Reserve",
    "shortName": "Nyakasanga",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      31.55,
      -17.35
    ],
    "areaHa": 130000,
    "seed": 1392,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.041,
    "creditsIssued": 190000,
    "creditsRetired": 117800,
    "pricePerCredit": 5,
    "featured": false,
    "real": false,
    "hostCellId": "KZ31.3_-17.6",
    "parcel": {
      "id": "KZ-1392-footprint",
      "bbox": [
        31.3803,
        -17.513,
        31.7197,
        -17.187
      ],
      "center": [
        31.55,
        -17.35
      ],
      "label": null,
      "areaKm2": 1308.7,
      "landKm2": 1308.7,
      "forest2008Km2": 52,
      "preClearedKm2": 3.4,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 1.009,
        "2009": 1.346,
        "2010": 0.234,
        "2011": 0.61,
        "2012": 0.501,
        "2013": 0.29,
        "2014": 0.794,
        "2015": 0.596,
        "2016": 0.343,
        "2017": 0.881,
        "2018": 0.33,
        "2019": 0.231
      },
      "protectedFrac": 0,
      "elevationM": 1029,
      "ruggednessM": 74,
      "precipMmYr": 807
    }
  },
  {
    "id": "KZ-1465",
    "name": "Sebungwe Escarpment Project",
    "shortName": "Sebungwe",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      34.05,
      -17.35
    ],
    "areaHa": 310000,
    "seed": 1465,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.03,
    "creditsIssued": 330000,
    "creditsRetired": 99000,
    "pricePerCredit": 8.5,
    "featured": false,
    "real": false,
    "hostCellId": "KZ33.8_-17.6",
    "parcel": {
      "id": "KZ-1465-footprint",
      "bbox": [
        33.788,
        -17.6018,
        34.312,
        -17.0982
      ],
      "center": [
        34.05,
        -17.35
      ],
      "label": null,
      "areaKm2": 3121.3,
      "landKm2": 3121.3,
      "forest2008Km2": 359.9,
      "preClearedKm2": 7.3,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 0.808,
        "2009": 2.393,
        "2010": 3.043,
        "2011": 0.054,
        "2012": 1.16,
        "2013": 0.82,
        "2014": 0.466,
        "2015": 0.758,
        "2016": 0.639,
        "2017": 1.377,
        "2018": 1.25,
        "2019": 0.75
      },
      "protectedFrac": 0,
      "elevationM": 374,
      "ruggednessM": 85,
      "precipMmYr": 739
    }
  },
  {
    "id": "KZ-1538",
    "name": "Gokwe Forest Concession",
    "shortName": "Gokwe",
    "country": "Zimbabwe",
    "locality": "Zambezi Valley",
    "center": [
      29.05,
      -15.35
    ],
    "areaHa": 150000,
    "seed": 1538,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 4,
    "claimedBaselineLoss": 0.03,
    "creditsIssued": 160000,
    "creditsRetired": 60800,
    "pricePerCredit": 7.5,
    "featured": false,
    "real": false,
    "hostCellId": "KZ28.8_-15.6",
    "parcel": {
      "id": "KZ-1538-footprint",
      "bbox": [
        28.8696,
        -15.5251,
        29.2304,
        -15.1749
      ],
      "center": [
        29.05,
        -15.35
      ],
      "label": null,
      "areaKm2": 1509.9,
      "landKm2": 1509.9,
      "forest2008Km2": 114.5,
      "preClearedKm2": 11.1,
      "nonForestKm2": 0,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 2.128,
        "2009": 0.445,
        "2010": 0.123,
        "2011": 0.44,
        "2012": 0.5,
        "2013": 0.343,
        "2014": 0.652,
        "2015": 0.932,
        "2016": 0.653,
        "2017": 1.605,
        "2018": 1.198,
        "2019": 0.448
      },
      "protectedFrac": 0,
      "elevationM": 1127,
      "ruggednessM": 91,
      "precipMmYr": 795
    }
  }
];
