// projects.js — GENERATED by tools/make-projects.mjs. Do not edit by hand.
//
// Project names, registry status, claimed baselines and credit volumes are
// ILLUSTRATIVE. They are not real registry entries and name no real party.
//
// What is real: `parcel`, the INPE PRODES deforestation measured over each
// project's own footprint, and every control it is compared against.
//
// To add a real registered project, append a record with its published boundary,
// registry reference, methodology and baseline, then write its sourced case
// study in caseStudies.js.

export const REGION = {
  name: "Brazilian Legal Amazon",
  center: [-60.53, -5.52],
  zoom: 5.1,
  // What the overview frames: every project footprint on the map, and nothing
  // else. This used to be the whole parcel grid — 31 by 22 degrees, most of it
  // ground the overview never draws on — which cost about two thirds of a zoom
  // stop and left the thirteen projects huddled in the middle of empty forest.
  bounds: [[-69.9, -12.81], [-51.16, 1.77]],
  // Every parcel the map is able to draw. Comparables are matched on covariates
  // rather than on distance, so one can land anywhere in this grid, and a viewer
  // has to be able to pan to whatever the map has drawn. That is the only reason
  // the barrier is ever wider than the frame.
  reach: [[-74, -17], [-43, 5]],
  // Air left around the region, as a fraction of each axis, split between the
  // two sides. Room to move, well short of the whole continent.
  slack: 0.25,
  // The barrier that holds until the first frame lands, and nothing more.
  //
  // maplibre will not let the viewport show more than maxBounds, so it raises
  // the zoom floor until the bounds fill the window: the bounds, not minZoom,
  // are what set the limit. That makes a hand-written barrier a trap. Draw it
  // tight and it forbids the very overview it exists to protect — which is how
  // the old 35-degree box made its own shipped z4.3 unreachable. Draw it loose
  // enough to be safe at every window size and zooming out lands on Peru.
  //
  // The size that is right depends on the window, because padding is paid in
  // pixels and not in degrees: under 900px the panel becomes a bottom sheet over
  // half the screen, and framing the projects above it means rendering a lot of
  // empty map below them. So MapView measures the barrier off the overview it
  // actually produced (see `panBarrier`) rather than guessing here. This value
  // only has to hold for the second before the map loads, and it is a subset of
  // every barrier that computation can return.
  maxBounds: [[-77.8, -19.7], [-39.2, 7.7]],
};

export const PROJECTS = [
  {
    "id": "PJ-4100",
    "name": "Rio Aripuanã Conservation Concession",
    "shortName": "Aripuanã",
    "country": "Brazil",
    "locality": "Aripuanã",
    "center": [
      -59.5,
      -9.5
    ],
    "areaHa": 640000,
    "seed": 4100,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.127,
    "creditsIssued": 700000,
    "creditsRetired": 245000,
    "pricePerCredit": 4.2,
    "featured": true,
    "hostCellId": "C-60_-10",
    "parcel": {
      "id": "PJ-4100-footprint",
      "bbox": [
        -59.8643,
        -9.8617,
        -59.1357,
        -9.1383
      ],
      "center": [
        -59.5,
        -9.5
      ],
      "label": "Aripuanã",
      "areaKm2": 6398.8,
      "landKm2": 6379.2,
      "forest2008Km2": 4201.3,
      "preClearedKm2": 2175.8,
      "nonForestKm2": 2.1,
      "waterKm2": 19.6,
      "clearedByYear": {
        "2008": 71.456,
        "2009": 36.519,
        "2010": 43.512,
        "2011": 51.076,
        "2012": 46.948,
        "2013": 97.026,
        "2014": 90.825,
        "2015": 114.296,
        "2016": 101.225,
        "2017": 61.337,
        "2018": 81.215,
        "2019": 55.266,
        "2020": 69.697,
        "2021": 54.412,
        "2022": 171.238,
        "2023": 64.229
      },
      "protectedFrac": 0.194,
      "elevationM": 200,
      "ruggednessM": 86,
      "precipMmYr": 1895
    }
  },
  {
    "id": "PJ-4237",
    "name": "Serra do Cachimbo REDD+",
    "shortName": "Cachimbo",
    "country": "Brazil",
    "locality": "Novo Progresso",
    "center": [
      -55.5,
      -7.5
    ],
    "areaHa": 820000,
    "seed": 4237,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.144,
    "creditsIssued": 900000,
    "creditsRetired": 477000,
    "pricePerCredit": 6.4,
    "featured": true,
    "hostCellId": "C-56_-8",
    "parcel": {
      "id": "PJ-4237-footprint",
      "bbox": [
        -55.9102,
        -7.9095,
        -55.0898,
        -7.0905
      ],
      "center": [
        -55.5,
        -7.5
      ],
      "label": "Novo Progresso",
      "areaKm2": 8199.8,
      "landKm2": 8144.1,
      "forest2008Km2": 5149.3,
      "preClearedKm2": 2967.1,
      "nonForestKm2": 27.7,
      "waterKm2": 55.7,
      "clearedByYear": {
        "2008": 114.647,
        "2009": 172.644,
        "2010": 17.208,
        "2011": 24.183,
        "2012": 34.482,
        "2013": 54.107,
        "2014": 64.698,
        "2015": 35.008,
        "2016": 36.824,
        "2017": 21.281,
        "2018": 103.613,
        "2019": 71.699,
        "2020": 158.014,
        "2021": 133.737,
        "2022": 104.697,
        "2023": 53.715
      },
      "protectedFrac": 0.472,
      "elevationM": 269,
      "ruggednessM": 27,
      "precipMmYr": 2449
    }
  },
  {
    "id": "PJ-4374",
    "name": "Igarapé Tucumã Forest Project",
    "shortName": "Tucumã",
    "country": "Brazil",
    "locality": "Porto Velho",
    "center": [
      -65.5,
      -9.5
    ],
    "areaHa": 310000,
    "seed": 4374,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.148,
    "creditsIssued": 400000,
    "creditsRetired": 284000,
    "pricePerCredit": 8.6,
    "featured": false,
    "hostCellId": "C-66_-10",
    "parcel": {
      "id": "PJ-4374-footprint",
      "bbox": [
        -65.7536,
        -9.7518,
        -65.2464,
        -9.2482
      ],
      "center": [
        -65.5,
        -9.5
      ],
      "label": "Porto Velho",
      "areaKm2": 3100.9,
      "landKm2": 3063.2,
      "forest2008Km2": 0,
      "preClearedKm2": 4255.6,
      "nonForestKm2": 22.6,
      "waterKm2": 37.7,
      "clearedByYear": {
        "2008": 7.204,
        "2009": 17.144,
        "2010": 5.972,
        "2011": 13.172,
        "2012": 15.278,
        "2013": 17.97,
        "2014": 26.978,
        "2015": 52.208,
        "2016": 71.076,
        "2017": 64.948,
        "2018": 33.412,
        "2019": 82.807,
        "2020": 86.668,
        "2021": 84.327,
        "2022": 100.652,
        "2023": 33.497
      },
      "protectedFrac": 0.25,
      "elevationM": 152,
      "ruggednessM": 39,
      "precipMmYr": 2106
    }
  },
  {
    "id": "PJ-4511",
    "name": "Alto Juruena REDD+",
    "shortName": "Juruena",
    "country": "Brazil",
    "locality": "Costa Marques",
    "center": [
      -64.5,
      -12.5
    ],
    "areaHa": 470000,
    "seed": 4511,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.144,
    "creditsIssued": 500000,
    "creditsRetired": 220000,
    "pricePerCredit": 5.85,
    "featured": false,
    "hostCellId": "C-65_-13",
    "parcel": {
      "id": "PJ-4511-footprint",
      "bbox": [
        -64.8154,
        -12.81,
        -64.1846,
        -12.19
      ],
      "center": [
        -64.5,
        -12.5
      ],
      "label": "Costa Marques",
      "areaKm2": 4699.9,
      "landKm2": 4690,
      "forest2008Km2": 700.3,
      "preClearedKm2": 3544.2,
      "nonForestKm2": 445.5,
      "waterKm2": 9.9,
      "clearedByYear": {
        "2008": 23.024,
        "2009": 4.128,
        "2010": 6.465,
        "2011": 2.781,
        "2012": 1.26,
        "2013": 7.611,
        "2014": 3.087,
        "2015": 5.118,
        "2016": 6.694,
        "2017": 3.291,
        "2018": 5.825,
        "2019": 6.224,
        "2020": 10.309,
        "2021": 7.761,
        "2022": 4.142,
        "2023": 6.701
      },
      "protectedFrac": 0.111,
      "elevationM": 148,
      "ruggednessM": 9,
      "precipMmYr": 1898
    }
  },
  {
    "id": "PJ-4648",
    "name": "Castanheira Forest Reserve",
    "shortName": "Castanheira",
    "country": "Brazil",
    "locality": "Candeias do Jamari",
    "center": [
      -63.5,
      -8.5
    ],
    "areaHa": 260000,
    "seed": 4648,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.326,
    "creditsIssued": 700000,
    "creditsRetired": 434000,
    "pricePerCredit": 8.05,
    "featured": false,
    "hostCellId": "C-64_-9",
    "parcel": {
      "id": "PJ-4648-footprint",
      "bbox": [
        -63.7316,
        -8.7306,
        -63.2684,
        -8.2694
      ],
      "center": [
        -63.5,
        -8.5
      ],
      "label": "Candeias do Jamari",
      "areaKm2": 2600.7,
      "landKm2": 2389.3,
      "forest2008Km2": 0,
      "preClearedKm2": 2747.4,
      "nonForestKm2": 129.7,
      "waterKm2": 211.4,
      "clearedByYear": {
        "2008": 13.204,
        "2009": 4.333,
        "2010": 6.793,
        "2011": 4.221,
        "2012": 5.519,
        "2013": 15.403,
        "2014": 10.964,
        "2015": 14.795,
        "2016": 25.121,
        "2017": 25.069,
        "2018": 12.353,
        "2019": 16.303,
        "2020": 24.723,
        "2021": 34.307,
        "2022": 18.15,
        "2023": 12.911
      },
      "protectedFrac": 0.472,
      "elevationM": 83,
      "ruggednessM": 10,
      "precipMmYr": 2600
    }
  },
  {
    "id": "PJ-4785",
    "name": "Vale do Guaporé REDD+",
    "shortName": "Guaporé",
    "country": "Brazil",
    "locality": "Brasiléia",
    "center": [
      -69.5,
      -10.5
    ],
    "areaHa": 730000,
    "seed": 4785,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.143,
    "creditsIssued": 800000,
    "creditsRetired": 280000,
    "pricePerCredit": 5.3,
    "featured": false,
    "hostCellId": "C-70_-11",
    "parcel": {
      "id": "PJ-4785-footprint",
      "bbox": [
        -69.8903,
        -10.8863,
        -69.1097,
        -10.1137
      ],
      "center": [
        -69.5,
        -10.5
      ],
      "label": "Brasiléia",
      "areaKm2": 7299.2,
      "landKm2": 7299.2,
      "forest2008Km2": 5440.5,
      "preClearedKm2": 1858.2,
      "nonForestKm2": 0.5,
      "waterKm2": 0,
      "clearedByYear": {
        "2008": 10.753,
        "2009": 4.409,
        "2010": 11.131,
        "2011": 10.128,
        "2012": 8.142,
        "2013": 14.556,
        "2014": 26.999,
        "2015": 16.748,
        "2016": 12.051,
        "2017": 21.218,
        "2018": 15.601,
        "2019": 63.788,
        "2020": 46.912,
        "2021": 58.477,
        "2022": 21.769,
        "2023": 21.851
      },
      "protectedFrac": 0.528,
      "elevationM": 282,
      "ruggednessM": 29,
      "precipMmYr": 1898
    }
  },
  {
    "id": "PJ-4922",
    "name": "Rio Manicoré Conservation",
    "shortName": "Manicoré",
    "country": "Brazil",
    "locality": "Portel",
    "center": [
      -51.5,
      -2.5
    ],
    "areaHa": 550000,
    "seed": 4922,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.172,
    "creditsIssued": 800000,
    "creditsRetired": 424000,
    "pricePerCredit": 7.5,
    "featured": false,
    "hostCellId": "C-52_-3",
    "parcel": {
      "id": "PJ-4922-footprint",
      "bbox": [
        -51.8334,
        -2.8354,
        -51.1666,
        -2.1646
      ],
      "center": [
        -51.5,
        -2.5
      ],
      "label": "Portel",
      "areaKm2": 5500.5,
      "landKm2": 2794.6,
      "forest2008Km2": 1413,
      "preClearedKm2": 1334.1,
      "nonForestKm2": 47.5,
      "waterKm2": 2705.9,
      "clearedByYear": {
        "2008": 20.3,
        "2009": 2.613,
        "2010": 5.382,
        "2011": 14.511,
        "2012": 0.871,
        "2013": 2.539,
        "2014": 2.24,
        "2015": 11.054,
        "2016": 10.229,
        "2017": 11.208,
        "2018": 18.836,
        "2019": 37.201,
        "2020": 31.186,
        "2021": 39.82,
        "2022": 83.764,
        "2023": 41.664
      },
      "protectedFrac": 0.167,
      "elevationM": 62,
      "ruggednessM": 18,
      "precipMmYr": 1970
    }
  },
  {
    "id": "PJ-5059",
    "name": "Serra Verde REDD+",
    "shortName": "Serra Verde",
    "country": "Brazil",
    "locality": "Curuá",
    "center": [
      -55.5,
      -1.5
    ],
    "areaHa": 390000,
    "seed": 5059,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.478,
    "creditsIssued": 1500000,
    "creditsRetired": 1065000,
    "pricePerCredit": 4.75,
    "featured": false,
    "hostCellId": "C-56_-2",
    "parcel": {
      "id": "PJ-5059-footprint",
      "bbox": [
        -55.7806,
        -1.7824,
        -55.2194,
        -1.2176
      ],
      "center": [
        -55.5,
        -1.5
      ],
      "label": "Curuá",
      "areaKm2": 3900.2,
      "landKm2": 2745.8,
      "forest2008Km2": 0,
      "preClearedKm2": 2534.7,
      "nonForestKm2": 760.1,
      "waterKm2": 1154.4,
      "clearedByYear": {
        "2008": 34.686,
        "2009": 19.162,
        "2010": 30.157,
        "2011": 10.771,
        "2012": 6.465,
        "2013": 15.118,
        "2014": 16.808,
        "2015": 10.465,
        "2016": 6.119,
        "2017": 16.965,
        "2018": 21.708,
        "2019": 28.52,
        "2020": 39.548,
        "2021": 31.578,
        "2022": 31.067,
        "2023": 23.275
      },
      "protectedFrac": 0.194,
      "elevationM": 124,
      "ruggednessM": 89,
      "precipMmYr": 2317
    }
  },
  {
    "id": "PJ-5196",
    "name": "Baixo Xingu Forest Project",
    "shortName": "Baixo Xingu",
    "country": "Brazil",
    "locality": "Uruará",
    "center": [
      -53.5,
      -3.5
    ],
    "areaHa": 880000,
    "seed": 5196,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.146,
    "creditsIssued": 1000000,
    "creditsRetired": 440000,
    "pricePerCredit": 6.95,
    "featured": false,
    "hostCellId": "C-54_-4",
    "parcel": {
      "id": "PJ-5196-footprint",
      "bbox": [
        -53.9221,
        -3.9242,
        -53.0779,
        -3.0758
      ],
      "center": [
        -53.5,
        -3.5
      ],
      "label": "Uruará",
      "areaKm2": 8799.6,
      "landKm2": 8278.8,
      "forest2008Km2": 4990,
      "preClearedKm2": 3288.8,
      "nonForestKm2": 0,
      "waterKm2": 520.8,
      "clearedByYear": {
        "2008": 56.649,
        "2009": 65.255,
        "2010": 50.87,
        "2011": 27.806,
        "2012": 36.33,
        "2013": 40.568,
        "2014": 14.957,
        "2015": 29.551,
        "2016": 34.35,
        "2017": 103.475,
        "2018": 50.686,
        "2019": 98.233,
        "2020": 76.6,
        "2021": 91.826,
        "2022": 115.153,
        "2023": 71.067
      },
      "protectedFrac": 0.083,
      "elevationM": 165,
      "ruggednessM": 52,
      "precipMmYr": 2153
    }
  },
  {
    "id": "PJ-5333",
    "name": "Rio Tapauá REDD+",
    "shortName": "Tapauá",
    "country": "Brazil",
    "locality": "Rurópolis",
    "center": [
      -55.5,
      -4.5
    ],
    "areaHa": 420000,
    "seed": 5333,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.247,
    "creditsIssued": 800000,
    "creditsRetired": 496000,
    "pricePerCredit": 4.2,
    "featured": false,
    "hostCellId": "C-56_-5",
    "parcel": {
      "id": "PJ-5333-footprint",
      "bbox": [
        -55.792,
        -4.793,
        -55.208,
        -4.207
      ],
      "center": [
        -55.5,
        -4.5
      ],
      "label": "Rurópolis",
      "areaKm2": 4199.5,
      "landKm2": 3960.6,
      "forest2008Km2": 773.6,
      "preClearedKm2": 3187,
      "nonForestKm2": 0,
      "waterKm2": 238.9,
      "clearedByYear": {
        "2008": 21.254,
        "2009": 21.162,
        "2010": 11.236,
        "2011": 20.161,
        "2012": 11.723,
        "2013": 13.601,
        "2014": 22.751,
        "2015": 13.793,
        "2016": 14.857,
        "2017": 28.874,
        "2018": 20.521,
        "2019": 73.948,
        "2020": 71.7,
        "2021": 135.329,
        "2022": 71.761,
        "2023": 29.591
      },
      "protectedFrac": 0.389,
      "elevationM": 210,
      "ruggednessM": 78,
      "precipMmYr": 2927
    }
  },
  {
    "id": "PJ-5470",
    "name": "Campos Lindos Conservation",
    "shortName": "Campos Lindos",
    "country": "Brazil",
    "locality": "Nova Monte Verde",
    "center": [
      -57.5,
      -9.5
    ],
    "areaHa": 200000,
    "seed": 5470,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.318,
    "creditsIssued": 500000,
    "creditsRetired": 175000,
    "pricePerCredit": 6.4,
    "featured": false,
    "hostCellId": "C-58_-10",
    "parcel": {
      "id": "PJ-5470-footprint",
      "bbox": [
        -57.7037,
        -9.7022,
        -57.2963,
        -9.2978
      ],
      "center": [
        -57.5,
        -9.5
      ],
      "label": "Nova Monte Verde",
      "areaKm2": 2000.1,
      "landKm2": 1969.3,
      "forest2008Km2": 0,
      "preClearedKm2": 3535.3,
      "nonForestKm2": 12.6,
      "waterKm2": 30.8,
      "clearedByYear": {
        "2008": 25.885,
        "2009": 7.563,
        "2010": 7.922,
        "2011": 8.009,
        "2012": 5.849,
        "2013": 9.342,
        "2014": 6.119,
        "2015": 5.485,
        "2016": 10.242,
        "2017": 7.252,
        "2018": 11.038,
        "2019": 32.796,
        "2020": 20.011,
        "2021": 32.728,
        "2022": 26.678,
        "2023": 28.08
      },
      "protectedFrac": 0.167,
      "elevationM": 292,
      "ruggednessM": 41,
      "precipMmYr": 1713
    }
  },
  {
    "id": "PJ-5607",
    "name": "Alto Purus Forest Reserve",
    "shortName": "Alto Purus",
    "country": "Brazil",
    "locality": "Manaquiri",
    "center": [
      -60.5,
      -3.5
    ],
    "areaHa": 610000,
    "seed": 5607,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.136,
    "creditsIssued": 700000,
    "creditsRetired": 371000,
    "pricePerCredit": 8.6,
    "featured": false,
    "hostCellId": "C-61_-4",
    "parcel": {
      "id": "PJ-5607-footprint",
      "bbox": [
        -60.8515,
        -3.8532,
        -60.1485,
        -3.1468
      ],
      "center": [
        -60.5,
        -3.5
      ],
      "label": "Manaquiri",
      "areaKm2": 6101.3,
      "landKm2": 3447.4,
      "forest2008Km2": 789.5,
      "preClearedKm2": 2004.4,
      "nonForestKm2": 653.5,
      "waterKm2": 2653.9,
      "clearedByYear": {
        "2008": 2.894,
        "2009": 11.976,
        "2010": 11.236,
        "2011": 6.649,
        "2012": 1.491,
        "2013": 4.207,
        "2014": 1.652,
        "2015": 8.548,
        "2016": 2.374,
        "2017": 1.731,
        "2018": 1.441,
        "2019": 4.715,
        "2020": 7.042,
        "2021": 3.78,
        "2022": 1.593,
        "2023": 6.506
      },
      "protectedFrac": 0.222,
      "elevationM": 27,
      "ruggednessM": 11,
      "precipMmYr": 2684
    }
  },
  {
    "id": "PJ-5744",
    "name": "Rio Anajás Forest Project",
    "shortName": "Anajás",
    "country": "Brazil",
    "locality": "São Luiz",
    "center": [
      -60.5,
      1.5
    ],
    "areaHa": 350000,
    "seed": 5744,
    "registry": "Illustrative record",
    "methodology": "Reference-area baseline",
    "startYear": 2016,
    "creditingYears": 8,
    "claimedBaselineLoss": 0.153,
    "creditsIssued": 400000,
    "creditsRetired": 284000,
    "pricePerCredit": 5.85,
    "featured": false,
    "hostCellId": "C-61_1",
    "parcel": {
      "id": "PJ-5744-footprint",
      "bbox": [
        -60.7658,
        1.2325,
        -60.2342,
        1.7675
      ],
      "center": [
        -60.5,
        1.5
      ],
      "label": "São Luiz",
      "areaKm2": 3499.6,
      "landKm2": 3426.4,
      "forest2008Km2": 310.2,
      "preClearedKm2": 1302,
      "nonForestKm2": 1814.2,
      "waterKm2": 73.2,
      "clearedByYear": {
        "2008": 5.226,
        "2009": 2.595,
        "2010": 6.71,
        "2011": 7.027,
        "2012": 4.63,
        "2013": 5.081,
        "2014": 10.595,
        "2015": 5.384,
        "2016": 16.496,
        "2017": 7.095,
        "2018": 6.264,
        "2019": 33.872,
        "2020": 11.149,
        "2021": 12.94,
        "2022": 14.667,
        "2023": 20.392
      },
      "protectedFrac": 0.028,
      "elevationM": 98,
      "ruggednessM": 27,
      "precipMmYr": 2814
    }
  }
];
