"""Adapter for the PRODES parcel dataset already collected in this repository.

`src/cells.json` holds 277 one-degree parcels of the Brazilian Legal Amazon with
annual clear-cut increments 2008-2023, measured from INPE PRODES via the
TerraBrasilis WFS, plus elevation and rainfall from Open-Meteo. It was built by
`tools/collect.mjs` and it is real observed history - not modelled, not
simulated, no API keys involved.

Reusing it means the Python engine runs against measured forest loss from its
first commit rather than against fixtures. That matters more than it sounds:
synthetic data is generated by assumptions, and an estimator validated only on
synthetic data has been validated against the assumptions of whoever wrote the
generator.

What this adapter must be honest about:

  - Parcels are 1 degree, roughly 12,000 km2 at these latitudes. That is coarse.
    Loss rates measured on parcels that large average over a lot of internal
    variation.
  - Parcel areas come from WFS bounding-box queries, so a polygon straddling a
    parcel edge is counted whole on both sides. This slightly understates the
    forest denominator near large water bodies and non-forest patches, which
    slightly overstates loss rates. The error is symmetric between project and
    controls, so the comparison absorbs most of it, but absolute rates are
    approximate.
  - PRODES measures clear-cut deforestation in the Brazilian Amazon. It does not
    capture degradation, and it does not exist elsewhere.
  - Rainfall is null throughout: the Open-Meteo daily quota ran out during
    collection. Null, not zero - the matcher skips it rather than treating every
    parcel as a desert.

The claim side of the shipped projects is illustrative and is labelled as such;
see `load_projects`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Sequence

from ...models.forest_cell import ForestUnit, UnitPool
from ...models.project import CarbonProject, ProjectClaim
from ...models.provenance import DataProvenance, Provenance
from ..data_source import DataSourceError

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_CELLS = REPO_ROOT / "src" / "cells.json"
DEFAULT_PROJECTS = REPO_ROOT / "src" / "projects.js"


def _parse_projects_js(path: Path) -> list[dict[str, Any]]:
    """Pull the PROJECTS array out of the generated JavaScript module.

    `tools/make-projects.mjs` writes it with JSON.stringify, so the array itself
    is valid JSON even though the file around it is not. Slicing between the
    export and its terminator is enough, and it avoids either duplicating the
    dataset into a second file that can drift or requiring a Node process at
    import time.
    """
    text = path.read_text(encoding="utf-8")
    match = re.search(r"export const PROJECTS = (\[.*?\n\]);", text, re.DOTALL)
    if not match:
        raise DataSourceError(
            f"could not find the PROJECTS array in {path}. If the generator's output "
            f"format changed, this adapter needs updating rather than guessing."
        )
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError as exc:
        raise DataSourceError(f"PROJECTS array in {path} is not valid JSON: {exc}") from exc


def _covariates_from_record(record: dict[str, Any]) -> dict[str, float | None]:
    """Map the collected fields onto the engine's covariate names.

    Only what was actually measured is mapped. Roads, settlements, population and
    cropland are not in this dataset, so they are absent from the mapping
    entirely and the matcher will report matching on nine covariates rather than
    twelve. Filling them with continental averages would look better and mean
    less.
    """
    land = record.get("landKm2") or 0.0
    ruggedness = record.get("ruggednessM")
    return {
        "elevation": record.get("elevationM"),
        # Elevation spread inside the parcel, in metres, standing in for slope.
        # It is not slope in degrees, and it is not converted to pretend it is:
        # the matcher standardises every covariate anyway, so a monotone proxy
        # ranks parcels correctly, and calling it what it is keeps the
        # substitution visible to anyone reading the output.
        "slope": ruggedness,
        "precipitation": record.get("precipMmYr"),
        "latitude": record["center"][1],
        "prior_cleared_fraction": (
            (record.get("preClearedKm2") or 0.0) / land if land > 0 else None
        ),
        "distance_to_road": None,
        "distance_to_settlement": None,
        "population_density": None,
        "cropland_percentage": None,
    }


def _unit_from_record(
    record: dict[str, Any],
    provenance: DataProvenance,
    first_year: int,
    is_project: bool = False,
) -> ForestUnit:
    cleared = {int(y): float(v) for y, v in record["clearedByYear"].items()}
    land = float(record.get("landKm2") or record["areaKm2"])
    # Forest standing when the record opens: land less what was already cleared
    # and less the mapped non-forest and water. The collector stores this
    # directly for pool parcels; project footprints carry the same fields.
    forest_baseline = record.get("forest2008Km2")
    if forest_baseline is None:
        forest_baseline = max(
            0.0,
            land
            - float(record.get("preClearedKm2") or 0.0)
            - float(record.get("nonForestKm2") or 0.0),
        )
    return ForestUnit(
        unit_id=record["id"],
        centroid=(float(record["center"][0]), float(record["center"][1])),
        bbox=tuple(float(v) for v in record["bbox"]) if record.get("bbox") else None,
        land_km2=land,
        forest_baseline_km2=float(forest_baseline),
        first_year=first_year,
        cleared_km2_by_year=cleared,
        covariates=_covariates_from_record(record),
        label=record.get("label", ""),
        country="Brazil",
        ecoregion="Amazon",
        forest_type="tropical moist broadleaf",
        protected_fraction=float(record.get("protectedFrac") or 0.0),
        is_carbon_project=is_project,
        prior_cleared_km2=float(record.get("preClearedKm2") or 0.0),
        provenance=provenance,
    )


class ProdesCellSource:
    """Forest histories from INPE PRODES, as collected by `tools/collect.mjs`."""

    def __init__(
        self,
        cells_path: Path | str = DEFAULT_CELLS,
        projects_path: Path | str = DEFAULT_PROJECTS,
    ):
        self.cells_path = Path(cells_path)
        self.projects_path = Path(projects_path)
        if not self.cells_path.exists():
            raise DataSourceError(
                f"{self.cells_path} not found. Run `npm run collect` to build the "
                f"control pool from the public PRODES endpoints."
            )
        self._doc = json.loads(self.cells_path.read_text(encoding="utf-8"))

    # -- provenance ---------------------------------------------------------

    @property
    def provenance(self) -> DataProvenance:
        return DataProvenance(
            kind=Provenance.MEASURED,
            source=self._doc.get("source", "INPE PRODES via TerraBrasilis WFS"),
            citation=self._doc.get("citation", ""),
            license=self._doc.get("license", ""),
            collected_at=self._doc.get("collectedAt", ""),
            note=(
                "1-degree parcels; bounding-box aggregation counts straddling polygons "
                "whole, so absolute loss rates are approximate. Rainfall is unmeasured "
                "throughout this collection."
            ),
        )

    @property
    def first_year(self) -> int:
        return int(self._doc["firstYear"])

    @property
    def last_year(self) -> int:
        return int(self._doc["lastYear"])

    # -- loading ------------------------------------------------------------

    def load_pool(self) -> UnitPool:
        prov = self.provenance
        units = tuple(
            _unit_from_record(rec, prov, self.first_year) for rec in self._doc["cells"]
        )
        return UnitPool(
            units=units,
            provenance=prov,
            region=self._doc.get("region", "Brazilian Legal Amazon"),
            resolution_note=(
                f"{self._doc.get('cellDegrees', 1)} degree parcels, "
                f"{self.first_year}-{self.last_year}"
            ),
        )

    def load_projects(self) -> Sequence[CarbonProject]:
        """Projects with measured footprints and illustrative claims.

        The split is the important part and it is preserved rather than smoothed
        over. `parcel` is real: PRODES queried against each project's own
        boundary, the same measurement applied to the controls. The claimed
        baseline, credit volumes and registry status are illustrative - they
        exercise the interface and name no real party - so the claim carries
        ILLUSTRATIVE provenance and every result computed from it inherits the
        caveat automatically.
        """
        if not self.projects_path.exists():
            raise DataSourceError(f"{self.projects_path} not found")
        measured = self.provenance
        claim_prov = DataProvenance(
            kind=Provenance.ILLUSTRATIVE,
            source="tools/make-projects.mjs",
            note=(
                "Baselines, credit volumes and registry status are illustrative. They "
                "describe no real project and no real party. The forest measured under "
                "each footprint is real."
            ),
        )
        out: list[CarbonProject] = []
        for rec in _parse_projects_js(self.projects_path):
            footprint = _unit_from_record(
                rec["parcel"], measured, self.first_year, is_project=True
            )
            claim = ProjectClaim(
                baseline_loss=float(rec["claimedBaselineLoss"]),
                credits_issued=int(rec.get("creditsIssued") or 0),
                credits_retired=int(rec.get("creditsRetired") or 0),
                price_per_credit=rec.get("pricePerCredit"),
                methodology=rec.get("methodology", ""),
                registry=rec.get("registry", ""),
                provenance=claim_prov,
            )
            out.append(
                CarbonProject(
                    project_id=rec["id"],
                    name=rec["name"],
                    short_name=rec.get("shortName", ""),
                    start_year=int(rec["startYear"]),
                    crediting_years=int(rec.get("creditingYears") or 8),
                    footprint=footprint,
                    claim=claim,
                    country=rec.get("country", "Brazil"),
                    locality=rec.get("locality", ""),
                    host_unit_id=rec.get("hostCellId"),
                    area_ha=rec.get("areaHa"),
                )
            )
        return tuple(out)

    def load_project(self, project_id: str) -> CarbonProject | None:
        return next((p for p in self.load_projects() if p.project_id == project_id), None)
